FROM python:3.11-slim
WORKDIR /app
COPY backrun/requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt && rm -f /tmp/requirements.txt
COPY backrun /app
COPY config.yaml /app/config.yaml
COPY config /app/config
